### ISSUE TITLE
HW3 game에서 MakeArrayImpl 버전 문의드립니다

### ISSUE THREAD

**Issue by Logtic** [snu-sf-class/pp201902#26]
./compile.sh를 실행하면

java.io.IOException: Scala signature MakeArrayImpl has wrong version
 expected: 5.0
 found: 5.2 in MakeArrayImpl.class
	at scala.reflect.internal.pickling.UnPickler$Scan.checkVersion(UnPickler.scala:111)
	at scala.reflect.internal.pickling.UnPickler$Scan.<init>(UnPickler.scala:53)
	at scala.reflect.internal.pickling.UnPickler.unpickle(UnPickler.scala:40)
	at scala.tools.nsc.symtab.classfile.ClassfileParser.parseAttribute$1(ClassfileParser.scala:856)
	at scala.tools.nsc.symtab.classfile.ClassfileParser.$anonfun$parseAttributes$17(ClassfileParser.scala:1048)

이와 같은 에러가 뜹니다. 어떻게 해결해야할까요?

**Comment by Dongjoo-Kim** [comment]
scala version이 달라 생기는 에러로 추측됩니다.
깃헙 페이지에 공지되어 있는 버전인 2.13.0을 사용하기시 바랍니다.

scala version을 2.13.0으로 하여도 동일한 에러가 발생하신다면 java version도 아래와 같이 설정하시길 바랍니다.
```
openjdk 11.0.4 2019-07-16
OpenJDK Runtime Environment (build 11.0.4+11-post-Ubuntu-1ubuntu218.04.3)
OpenJDK 64-Bit Server VM (build 11.0.4+11-post-Ubuntu-1ubuntu218.04.3, mixed mode, sharing)
```

**Comment by Logtic** [comment]
![스크린샷, 2019-11-21 20-12-39](https://user-images.githubusercontent.com/12660068/69333044-4a0c3680-0c9b-11ea-8225-d2b4af528d77.png)
![스크린샷, 2019-11-21 20-12-19](https://user-images.githubusercontent.com/12660068/69333053-4d9fbd80-0c9b-11ea-90fd-18d0c8c295fd.png)

이렇게 했는데도 동일한 에러가 생깁니다.. ㅠㅠ

**Comment by Logtic** [comment]
스칼라에서 2.13.0-M1이 문제였네요 그냥 2.13.0으로 하니까 작동합니다!
감사합니다!
